// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1bd92cedbbf431b3 "Sentinel AI", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Wide Screen' | 'Laptop' | 'Tablet' | 'Phone' // Variant
 * headingLine1?: string // Heading - Line 1
 * headingLine2?: string // Heading - Line 2
 * subHeading?: string // Sub Heading
 * showTip?: boolean // Show Tip
 * textOnTip?: string // Text on Tip
}} Props

 */
import { BookFlip } from "./chunks/chunk-5ZU3NON3.js";
import { stdin_default } from "./chunks/chunk-QV6YFK4Z.js";
import "./chunks/chunk-A5VIV4BG.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-XSBYVWOY.js";
import "./chunks/chunk-W3MGGPGV.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-YC4JS6HC.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-SZHLSPRP.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-KDPSGK4W.js";
import { className, css, fonts } from "./chunks/chunk-K7JSNEXQ.js";
import { routes } from "./chunks/chunk-32AWGGTF.js";

// virtual:generations-images-section
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/egt1PlFRCvsXw2zQxkoq/8VOlnAgVoC306oa2FlX7/SzRnwX2wF.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var SmallHeadingWithLinesFonts = getFonts(stdin_default);
var BookFlipFonts = getFonts(BookFlip);
var cycleOrder = ["y3lJTdmqW", "qJwn7mn1e", "vm6P_s6xC", "XHtTc0LUO"];
var serializationHash = "framer-Bk1Dr";
var variantClassNames = {
	qJwn7mn1e: "framer-v-18r0f5c",
	vm6P_s6xC: "framer-v-1cp6mtq",
	XHtTc0LUO: "framer-v-zy3pbn",
	y3lJTdmqW: "framer-v-1a92xhf",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Wide Screen": "y3lJTdmqW",
	Laptop: "qJwn7mn1e",
	Phone: "XHtTc0LUO",
	Tablet: "vm6P_s6xC",
};
var getProps = ({
	headingLine1,
	headingLine2,
	height,
	id,
	showTip,
	subHeading,
	textOnTip,
	width,
	...props
}) => {
	return {
		...props,
		bzO1HIDvx: subHeading ?? props.bzO1HIDvx ?? "TYPES OF BIAS",
		L9xrqinvs: showTip ?? props.L9xrqinvs ?? true,
		s_xP1aLMD: headingLine2 ?? props.s_xP1aLMD ?? "Catch",
		sc5qVIRJL: headingLine1 ?? props.sc5qVIRJL ?? "What We",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "y3lJTdmqW",
		wkje9vCwU: textOnTip ?? props.wkje9vCwU ?? "Drag for Flip Pages",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		sc5qVIRJL: sc5qVIRJL2,
		s_xP1aLMD: s_xP1aLMD2,
		bzO1HIDvx: bzO1HIDvx2,
		L9xrqinvs: L9xrqinvs2,
		wkje9vCwU: wkje9vCwU2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "y3lJTdmqW",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className2,
		className,
		className4,
		className3,
		className5,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1a92xhf",
							className6,
							classNames,
						)}
						data-framer-name={"Wide Screen"}
						layoutDependency={layoutDependency}
						layoutId={"y3lJTdmqW"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, rgb(0, 0, 0) 40%, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) 100%)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								qJwn7mn1e: {
									"data-framer-name": "Laptop",
								},
								vm6P_s6xC: {
									"data-framer-name": "Tablet",
								},
								XHtTc0LUO: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1tz02r8"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"vEupR9ARH"}
						>
							<motion.div
								className={"framer-4pruwk"}
								data-framer-name={"Heading"}
								layoutDependency={layoutDependency}
								layoutId={"YkYiWAWlp"}
							>
								<motion.div
									className={"framer-1r4rvwl"}
									layoutDependency={layoutDependency}
									layoutId={"CBXEtnyIc"}
								>
									<motion.div
										className={"framer-9bdhfk"}
										layoutDependency={layoutDependency}
										layoutId={"K9KrgFhve"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-zszamf"}
											data-framer-name={"Line 1"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"eldFewon8"}
											style={{
												"--extracted-1of0zx5":
													"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												"--framer-paragraph-spacing": "0px",
											}}
											text={sc5qVIRJL2}
											variants={{
												vm6P_s6xC: {
													"--extracted-1k2zljd":
														"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												},
												XHtTc0LUO: {
													"--extracted-1wi65aa":
														"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												},
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													vm6P_s6xC: {
														children: (
															<React.Fragment>
																<motion.h3
																	className={"framer-styles-preset-wvy7ez"}
																	data-styles-preset={"hdCs32bmG"}
																	style={{
																		"--framer-text-alignment": "left",
																	}}
																>
																	<motion.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-1k2zljd, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																		}}
																	>
																		{"Our generations"}
																	</motion.span>
																</motion.h3>
															</React.Fragment>
														),
													},
													XHtTc0LUO: {
														children: (
															<React.Fragment>
																<motion.h4
																	className={"framer-styles-preset-19084qk"}
																	data-styles-preset={"D2Nj2b5ip"}
																	style={{
																		"--framer-text-alignment": "left",
																	}}
																>
																	<motion.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-1wi65aa, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																		}}
																	>
																		{"Our generations"}
																	</motion.span>
																</motion.h4>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h2
													className={"framer-styles-preset-ep0jra"}
													data-styles-preset={"hZ8usl_26"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1of0zx5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
													}}
												>
													{"Our generations"}
												</motion.h2>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-1iu28c5"}
										layoutDependency={layoutDependency}
										layoutId={"Ch6XKanJs"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-15u5ai8"}
											data-framer-name={"Line 2"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Ex5EwJcrE"}
											style={{
												"--extracted-1of0zx5":
													"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												"--framer-paragraph-spacing": "0px",
											}}
											text={s_xP1aLMD2}
											variants={{
												vm6P_s6xC: {
													"--extracted-1k2zljd":
														"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												},
												XHtTc0LUO: {
													"--extracted-1wi65aa":
														"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												},
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													vm6P_s6xC: {
														children: (
															<React.Fragment>
																<motion.h3
																	className={"framer-styles-preset-wvy7ez"}
																	data-styles-preset={"hdCs32bmG"}
																	style={{
																		"--framer-text-alignment": "left",
																	}}
																>
																	<motion.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-1k2zljd, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																		}}
																	>
																		{"with AI"}
																	</motion.span>
																</motion.h3>
															</React.Fragment>
														),
													},
													XHtTc0LUO: {
														children: (
															<React.Fragment>
																<motion.h4
																	className={"framer-styles-preset-19084qk"}
																	data-styles-preset={"D2Nj2b5ip"}
																	style={{
																		"--framer-text-alignment": "left",
																	}}
																>
																	<motion.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-1wi65aa, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																		}}
																	>
																		{"with AI"}
																	</motion.span>
																</motion.h4>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h2
													className={"framer-styles-preset-ep0jra"}
													data-styles-preset={"hZ8usl_26"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1of0zx5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
													}}
												>
													{"with AI"}
												</motion.h2>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1q2coik"}
											data-framer-name={"Dot"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"GizGLEStI"}
											style={{
												"--extracted-1of0zx5":
													"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
												"--framer-paragraph-spacing": "0px",
											}}
											variants={{
												vm6P_s6xC: {
													"--extracted-a0htzi":
														"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
												},
												XHtTc0LUO: {
													"--extracted-1eung3n":
														"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
												},
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													vm6P_s6xC: {
														children: (
															<React.Fragment>
																<motion.h3
																	className={"framer-styles-preset-wvy7ez"}
																	data-styles-preset={"hdCs32bmG"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-a0htzi, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
																	}}
																>
																	{"."}
																</motion.h3>
															</React.Fragment>
														),
													},
													XHtTc0LUO: {
														children: (
															<React.Fragment>
																<motion.h4
																	className={"framer-styles-preset-19084qk"}
																	data-styles-preset={"D2Nj2b5ip"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1eung3n, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
																	}}
																>
																	{"."}
																</motion.h4>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h2
													className={"framer-styles-preset-ep0jra"}
													data-styles-preset={"hZ8usl_26"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1of0zx5, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
													}}
												>
													{"."}
												</motion.h2>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
								<ComponentViewportProvider
									height={82}
									y={(componentViewport?.y || 0) + 0 + 0 + 250 + 0 + 0 + 88}
									{...addPropertyOverrides(
										{
											qJwn7mn1e: {
												y:
													(componentViewport?.y || 0) +
													0 +
													0 +
													150 +
													0 +
													0 +
													88,
											},
											vm6P_s6xC: {
												y:
													(componentViewport?.y || 0) +
													0 +
													0 +
													100 +
													0 +
													0 +
													32,
											},
											XHtTc0LUO: {
												width: `calc(min(${componentViewport?.width || "100vw"}, 1600px) - 40px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													0 +
													80 +
													0 +
													0 +
													125,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-xy45vh-container"}
										layoutDependency={layoutDependency}
										layoutId={"OF3jGzRlr-container"}
										nodeId={"OF3jGzRlr"}
										rendersWithMotion={true}
										scopeId={"SzRnwX2wF"}
									>
										{_jsx(stdin_default, {
											B4pJURn2f: true,
											height: "100%",
											id: "OF3jGzRlr",
											layoutId: "OF3jGzRlr",
											style: {
												width: "100%",
											},
											variant: "d3bH04UyF",
											width: "100%",
											zWunlxr_x: bzO1HIDvx2,
											...addPropertyOverrides(
												{
													vm6P_s6xC: {
														variant: "LCJjm_9gq",
													},
													XHtTc0LUO: {
														variant: "TjckuJE3n",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<motion.div
								className={"framer-euvoyh"}
								data-framer-name={"Spacer"}
								layoutDependency={layoutDependency}
								layoutId={"NdjMRu_Lt"}
							/>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1sw10rg-container"}
									isAuthoredByUser={true}
									layoutDependency={layoutDependency}
									layoutId={"N0C4ftZ4T-container"}
									nodeId={"N0C4ftZ4T"}
									rendersWithMotion={true}
									scopeId={"SzRnwX2wF"}
								>
									<BookFlip
										follow={0.25}
										height={"100%"}
										id={"N0C4ftZ4T"}
										images={[
											"https://framerusercontent.com/images/JOOrxOegRU6lmIGqqdrIc41W8NA.jpg?width=1024&height=1024",
											"https://framerusercontent.com/images/24QQu3tO5enbxFfnCyIunHUPGcI.png?width=804&height=1174",
											"https://framerusercontent.com/images/qYb0YBaSiPsFMvWfXFCBm0ltHw.png?width=960&height=1404",
											"https://framerusercontent.com/images/LojrFdcsw46oWF5w7zsy1tEs.png?width=964&height=1412",
											"https://framerusercontent.com/images/pmvCfT8cd9uQYGM4Ki7xCsI.png?width=808&height=1188",
											"https://framerusercontent.com/images/K3mOvv5bUlD6aGcRPzMXnknwQaw.jpg?width=1040&height=1384",
											"https://framerusercontent.com/images/9KH9CetWeBCCAOZr0UCVuTCIGhU.jpg?width=1040&height=1384",
											"https://framerusercontent.com/images/HmSmAWnd5TWWz8ziekZZkT10OQ.jpg?width=1040&height=1384",
											"https://framerusercontent.com/images/VeeL22OSboQXlkYl4t5obo9GC1w.png?width=1040&height=1384",
										]}
										initialPeek={0.4}
										layoutId={"N0C4ftZ4T"}
										maxRotDeg={180}
										pageHeight={650}
										pageWidth={400}
										perspective={1300}
										pxPerPage={300}
										radius={14}
										snapBias={0.5}
										style={{
											height: "100%",
											width: "100%",
										}}
										tiltDeg={-3}
										width={"100%"}
										{...addPropertyOverrides(
											{
												qJwn7mn1e: {
													pageHeight: 570,
													pageWidth: 350,
												},
												vm6P_s6xC: {
													pageHeight: 512,
													pageWidth: 315,
												},
												XHtTc0LUO: {
													pageHeight: 280,
													pageWidth: 170,
													perspective: 786,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							{L9xrqinvs2 !== false && (
								<motion.div
									className={"framer-d8nygx"}
									data-framer-name={"Tip"}
									layoutDependency={layoutDependency}
									layoutId={"BaZH5yn5R"}
								>
									<SVG
										className={"framer-cseopw"}
										data-framer-name={"Drag"}
										fill={
											'var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {"name":"White"} */'
										}
										intrinsicHeight={22}
										intrinsicWidth={25}
										layoutDependency={layoutDependency}
										layoutId={"FMwwSYMh2"}
										svg={
											'<svg width="25" height="22" viewBox="0 0 25 22" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g clip-path="url(#clip0_50_56)">\n<path d="M11.0297 20.6582L14.2022 20.6582C19.5311 20.6582 23.8511 16.3382 23.8511 11.0093C23.8511 5.68032 19.5311 1.36035 14.2021 1.36035L11.0297 1.36035C5.70073 1.36035 1.38077 5.68032 1.38077 11.0093C1.38077 16.3382 5.70074 20.6582 11.0297 20.6582Z" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M15.7054 7.60449L19.0759 11.01L15.7054 14.4155" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M9.46997 7.60449L6.09943 11.01L9.46997 14.4155" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M19.0759 11.0112L6.09933 11.0112" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<clipPath id="clip0_50_56">\n<rect width="22" height="25" fill="white" transform="translate(25 1.09278e-06) rotate(90)"/>\n</clipPath>\n</defs>\n</svg>\n'
										}
										withExternalLayout={true}
									/>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-v9670w"}
										data-framer-name={"Drag for flip pages."}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"SjMZv5Owm"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={wkje9vCwU2}
										verticalAlignment={"center"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												XHtTc0LUO: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-2q46y2"}
																data-styles-preset={"TUHGD6dmV"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																}}
															>
																{"Drag for Flip Pages"}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1ud6gfb"}
												data-styles-preset={"LFTrb0jZU"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
												}}
											>
												{"Drag for flip pages."}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							)}
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Bk1Dr.framer-1d188xl, .framer-Bk1Dr .framer-1d188xl { display: block; }",
	".framer-Bk1Dr.framer-1a92xhf { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1600px; }",
	".framer-Bk1Dr .framer-1tz02r8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; max-width: 1600px; overflow: visible; padding: 250px 100px 150px 100px; position: relative; width: 100%; z-index: 3; }",
	".framer-Bk1Dr .framer-4pruwk { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 5; }",
	".framer-Bk1Dr .framer-1r4rvwl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Bk1Dr .framer-9bdhfk { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Bk1Dr .framer-zszamf, .framer-Bk1Dr .framer-15u5ai8, .framer-Bk1Dr .framer-1q2coik, .framer-Bk1Dr .framer-v9670w { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-Bk1Dr .framer-1iu28c5 { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Bk1Dr .framer-xy45vh-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-Bk1Dr .framer-euvoyh { flex: none; height: 95px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; }",
	".framer-Bk1Dr .framer-1sw10rg-container { flex: none; height: 750px; position: relative; width: 100%; }",
	".framer-Bk1Dr .framer-d8nygx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Bk1Dr .framer-cseopw { flex: none; height: 22px; position: relative; width: 25px; }",
	".framer-Bk1Dr.framer-v-18r0f5c.framer-1a92xhf { width: 1200px; }",
	".framer-Bk1Dr.framer-v-18r0f5c .framer-1tz02r8 { padding: 150px 100px 150px 100px; }",
	".framer-Bk1Dr.framer-v-18r0f5c .framer-4pruwk, .framer-Bk1Dr.framer-v-1cp6mtq .framer-4pruwk { gap: 10px; }",
	".framer-Bk1Dr.framer-v-18r0f5c .framer-euvoyh { height: 25px; }",
	".framer-Bk1Dr.framer-v-18r0f5c .framer-1sw10rg-container { height: 710px; }",
	".framer-Bk1Dr.framer-v-1cp6mtq.framer-1a92xhf { width: 810px; }",
	".framer-Bk1Dr.framer-v-1cp6mtq .framer-1tz02r8 { padding: 100px 30px 100px 30px; }",
	".framer-Bk1Dr.framer-v-1cp6mtq .framer-euvoyh { height: 20px; }",
	".framer-Bk1Dr.framer-v-1cp6mtq .framer-1sw10rg-container { height: 625px; }",
	".framer-Bk1Dr.framer-v-zy3pbn.framer-1a92xhf { width: 390px; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-1tz02r8 { gap: 14px; padding: 80px 20px 80px 20px; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-4pruwk { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 35px; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-xy45vh-container { flex: none; width: 100%; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-euvoyh { height: 21px; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-1sw10rg-container { height: 344px; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-cseopw { aspect-ratio: 1.1363636363636365 / 1; height: var(--framer-aspect-ratio-supported, 22px); }",
	...css2,
	...css,
	...css4,
	...css3,
	...css5,
];
var FramerSzRnwX2wF = withCSS(Component, css6, "framer-Bk1Dr");
var stdin_default2 = FramerSzRnwX2wF;
FramerSzRnwX2wF.displayName = "Generations \u2013 Images \u2013 Section";
FramerSzRnwX2wF.defaultProps = {
	height: 1532,
	width: 1600,
};
addPropertyControls(FramerSzRnwX2wF, {
	variant: {
		options: ["y3lJTdmqW", "qJwn7mn1e", "vm6P_s6xC", "XHtTc0LUO"],
		optionTitles: ["Wide Screen", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	sc5qVIRJL: {
		defaultValue: "What We",
		displayTextArea: false,
		title: "Heading - Line 1",
		type: ControlType.String,
	},
	s_xP1aLMD: {
		defaultValue: "Catch",
		displayTextArea: false,
		title: "Heading - Line 2",
		type: ControlType.String,
	},
	bzO1HIDvx: {
		defaultValue: "TYPES OF BIAS",
		displayTextArea: false,
		title: "Sub Heading",
		type: ControlType.String,
	},
	L9xrqinvs: {
		defaultValue: true,
		title: "Show Tip",
		type: ControlType.Boolean,
	},
	wkje9vCwU: {
		defaultValue: "Drag for Flip Pages",
		displayTextArea: false,
		title: "Text on Tip",
		type: ControlType.String,
	},
});
addFonts(
	FramerSzRnwX2wF,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SmallHeadingWithLinesFonts,
		...BookFlipFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts5),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:generations-images-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "XHtTc0LUO",
	md: "vm6P_s6xC",
	xl: "qJwn7mn1e",
	"2xl": "y3lJTdmqW",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GenerationsImagesSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var generations_images_section_default = ComponentWithRoot;
export { generations_images_section_default as default };
